name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install deps and build
        run: |
          npm i && npm run build

      - name: Setup git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Stage changes
        run: |
          rm -rf .gitignore
          git rm -r --cached . 
          git add ./package.json ./node_modules ./dist
      
      - name: Commit changes
        run: |
          git commit -m "chore: add action"

      - name: Push to tag
        run: |
          git tag -d v1
          git tag -a v1 -m "chore: update v1 tag"
          git push --tags -f
      # # Compile dist/index.js and bundle with action.yml
      # # Force push major and minor tags, e.g. v1, v1.0
      # # See documentation: https://github.com/JasonEtco/build-and-tag-action
      # - uses: JasonEtco/build-and-tag-action@v2
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
