name: 'Run vitest tests'
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

    - name: Run `npm install`
      run: |
        npm install
        npm run build

    - name: Run vitest and report issues
      uses: ./
      with:
        config: ./vitest.config.ts
