name: "Run vitest tests - using roerohan/vitest-github-action@version"
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run `npm install`
        run: |
          npm install

      - name: Run vitest and report issues
        uses: roerohan/vitest-github-action@v1.3.16-testing.5
        with:
          config: ./vitest.config.ts
