name: "Run vitest tests"
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run `npm install`
        run: |
          npm install
          npm run build

      # - name: Run vitest and report issues
      #   uses: ./
      #   with:
      #     config: ./vitest.config.ts

      - name: Debugging
        run: |
          echo "Listing files in example directory"
          ls ./example

          echo "Logging all files in example directory"
          cat ./example/*.ts

          echo "Logging action.mjs"
          cat ./dist/action.mjs

          echo "Logging vitest config"
          cat ./vitest.config.ts

      - name: Run vitest and report issues
        uses: roerohan/vitest-github-action@v1
        with:
          config: ./vitest.config.ts
